src-include defaults feeds.conf.default
src-git small https://github.com/kenzok8/small.git;master
src-git third_party https://github.com/linkease/istore-packages.git;main
src-git diskman https://github.com/jjm2473/luci-app-diskman.git;dev
src-git oaf https://github.com/jjm2473/OpenAppFilter.git;dev7
